run_mode: debug
addr: 8080
name: ccServer
url: localhost:8080
version: v1
port: 8080
backend:
  mysql:
    conn:
      address: 124.222.48.125:3306
      user: ian
      password: l99l8ymm,e
      name: job
      ismigration: false
    mac:
      address: localhost:3306
      user: root
      password: root
      name: node
      ismigration: true
    mack8s:
      address: localhost:3306
      port: 3306
      user: root
      password: root
      name: topo
      ismigration: false
    win:
      address: localhost:3306
      user: root
      password: root
      name: go-ori
      ismigration: false
    wink8s:
      address: localhost:3306
      user: root
      password: root
      name: node
      ismigration: true
  redis:
    addr: 124.222.48.125:6379
    port: 6379
    isSentinal: false
    auth: i012nsl9
    masterName: mac
  zk:
    address:
      - localhost:2181
    auth: root
  prom:
    address: http://124.222.48.125:9090
    push: http://124.222.48.125:9091
    group: ian
  es:
    conn:
      address: "http://49.233.61.57:9211"  # 注意是http:// 必须要有
    local:
      address: "localhost:9200"  # 注意是http:// 必须要有
  jaeger:
    address: localhost:6831
  cluster:
    local:
      apiserver_address: "http://localhost:8080"
      config_address: "/Users/ian/.kube/config"
      is_in_cluster: false
      cluster: start.sh
      token: ""
    conn:
      apiserver_address: "http://localhost:8080"
      config_address: ""
      is_in_cluster: true
      cluster: test
      token: ""

client:
  CC:
    address: localhost:1129
    heart_beat: 10
    user: root
components:
  - cc
  - prom
  - jaeger
data:
  - mongo
  - zk
Cron:
#  - ian
#  - logger



