run_mode: debug
addr: 8080
name: ccServer
url: localhost:8080
version: v1
port: 8080
log:
  wirter: file,stdout
  logger_level: DEBUG
  logger_file: ~/log/goOrigin.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1024
  log_backup_count: 7
backend:
  MySql:
    address: localhost:3306
    port: 3306
    user: root
    password: root
  redis:
    address: localhost
    port: 6379
    isSentinal: false
    masterName: master
  etcd:
    address: localhost
    port: 2379
  mongo:
    address: localhost
    port: 27017
    user: root
    password: root
    db: ian

client:
  CC:
    address: localhost:1129
    heart_beat: 10
components:
  - mongo
  - redis
  - mysql
  - cc



