run_mode: debug
addr: 8080
name: ccServer
url: localhost:8080
version: v1
port: 8080
backend:
  MySql:
    address: 124.222.48.125:3306
    port: 3306
    user: ian
    password: l99l8ymm,e
    name: job
  redis:
    addr: 124.222.48.125:6379
    port: 6379
    isSentinal: false
    auth: i012nsl9
    masterName: master
  etcd:
    address: localhost
    port: 2379
  mongo:
    address: 124.222.48.125
    #    address: localhost
    port: 27017
    user: root
    password: rkkijoorkkiss312joo
    db: goOrigin
  zk:
    address:
      - localhost:2181
    auth: root
  k8s:
    address: /Users/ian/.kube/config
  prom:
    address: http://124.222.48.125:9090
    push: http://124.222.48.125:9091
    group: ian
  es:
    #    address: http://124.222.48.125:9200/
    #    address: http://localhost:9200/  # 注意是http:// 必须要有
    address: "http://49.233.61.57:9211"  # 注意是http:// 必须要有
  jaeger:
    address: localhost:6831
client:
  CC:
    address: localhost:1129
    heart_beat: 10
    user: root
components:
  - mysql
  - cc
  - prom
  - jaeger
  #  - redis
  #   - mongo
  #  - k8s
ssh:
  address: 113.31.168.103:22
  auth: 123qweasdzxc
  user: root
data:
  - mongo
  - zk
Cron:
#  - ian
#  - logger



