run_mode: debug
addr: 8080
name: ccServer
url: localhost:8080
version: v1
port: 8080
log:
  writer: file,stdout
  logger_level: DEBUG
  logger_file: ~/log/goOrigin.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1024
  log_backup_count: 7
backend:
  MySql:
    address: localhost:3306
    port: 3306
    user: root
    password: root
    name: ianTest
  redis:
    addr: 124.222.48.125:6379
    port: 6379
    isSentinal: false
    auth: i012nsl9
    masterName: master
  etcd:
    address: localhost
    port: 2379
  mongo:
    #    address: 124.222.48.125
    address: localhost
    port: 27017
    user: root
    password: rkkijoorkkiss312joo
    db: goOrigin
  zk:
    address:
      - localhost:2181
    auth: root
  k8s:
    address: /Users/ian/.kube/config
client:
  CC:
    address: localhost:1129
    heart_beat: 10
    user: root
components:
#  - redis
  #  - mysql
  - cc
#  - mongo
  - k8s
logging:
  fileName: .%Y%m%d%H
  level: debug
  path: logs
  rotation:
    time: 24 # 24 小时分割一次
    count: 50 # 最多50个
ssh:
  address: 113.31.168.103:22
  auth: 123qweasdzxc
  user: root
data:
  - mongo
  - zk
Cron:
  - ian



