run_mode: debug
addr: 8080
name: ccServer
url: localhost:8080
version: v1
log:
  wirter: file,stdout
  logger_level: DEBUG
  logger_file: ~/log/goOrigin.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1024
  log_backup_count: 7
backend:
  MySql:
    address: localhost
    port: 3306
    password: root
  redis:
    address: localhost
    port: 6379
    isSentinal: false
    masterName: master
  etcd:
    address: localhost
    port: 2379

