// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/ops/exec": {
            "get": {
                "tags": [
                    "任务"
                ],
                "summary": "执行",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "\"plan\"",
                            "\"main_job\""
                        ],
                        "type": "string",
                        "description": "任务类型 包括主 子 计划 agent 任务 .etc",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/ops/exec/main_job": {
            "post": {
                "tags": [
                    "MainJob"
                ],
                "summary": "主任务生成",
                "parameters": [
                    {
                        "description": "job",
                        "name": "plan",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.CreateMainJobRequestInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateMainJobResInfo"
                        }
                    }
                }
            }
        },
        "/v1/ops/exec/{version_id}": {
            "get": {
                "tags": [
                    "plan"
                ],
                "summary": "执行发布计划会滚",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "plan id",
                        "name": "plan_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/ops/main_job": {
            "get": {
                "tags": [
                    "MainJob"
                ],
                "summary": "主任务查看",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "job",
                        "name": "job_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.QueryMainJobResInfo"
                        }
                    }
                }
            }
        },
        "/v1/ops/plan": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "查看发布计划详情",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "name": "accessIds",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "name": "projectIds",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "name": "regionIds",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "templateId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.QueryPlanResponseInfo"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "创建发布计划",
                "parameters": [
                    {
                        "description": "计划",
                        "name": "plan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreatePlanRequestInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PlanResponseInfo"
                        }
                    }
                }
            }
        },
        "/v1/ops/revert": {
            "get": {
                "tags": [
                    "任务"
                ],
                "summary": "回滚",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "\"plan\"",
                            "\"main_job\""
                        ],
                        "type": "string",
                        "description": "任务类型 包括主 子 计划 agent 任务 .etc",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/v1/ops/revert/{version}": {
            "post": {
                "tags": [
                    "CC"
                ],
                "summary": "添加模板",
                "parameters": [
                    {
                        "description": "template",
                        "name": "addTemplate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddTemplateReq"
                        }
                    }
                ]
            }
        },
        "/v1/ops/stop": {
            "get": {
                "tags": [
                    "MainJob"
                ],
                "summary": "主任务暂停",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "main job",
                        "name": "plan",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/v1/ops/stop/{sub_job_id}": {
            "get": {
                "tags": [
                    "SubJob"
                ],
                "summary": "子任务暂停",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "sub job",
                        "name": "plan",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/v1/ops/sub_job": {
            "post": {
                "tags": [
                    "SubJob"
                ],
                "summary": "子任务创建",
                "parameters": [
                    {
                        "description": "job",
                        "name": "sub_job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateSubJobReqInfo"
                        }
                    }
                ]
            }
        },
        "/v1/ops/sub_job/": {
            "put": {
                "tags": [
                    "SubJob"
                ],
                "summary": "子任务更新",
                "parameters": [
                    {
                        "description": "job",
                        "name": "sub_job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateSubJobReqInfo"
                        }
                    }
                ]
            }
        },
        "/v1/ops/sub_job/{id}": {
            "get": {
                "tags": [
                    "SubJob"
                ],
                "summary": "子任务详情",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "mainJobId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "子任务 module 一对一",
                        "name": "moduleId",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "顺序",
                        "name": "rank",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "执行目标",
                        "name": "target",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "类型",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.QuerySubJobResInfo"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "SubJob"
                ],
                "summary": "子任务删除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "sub_job",
                        "name": "sub_job_id",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/v1/ops/{plan_id}": {
            "delete": {
                "description": "不支持批量删除",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "删除发布计划",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "plan id",
                        "name": "plan_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AddTemplateReq": {
            "type": "object",
            "properties": {
                "check": {
                    "description": "check",
                    "type": "boolean"
                },
                "config": {
                    "description": "config 配置文件地址",
                    "type": "string"
                },
                "content": {
                    "description": "content  模板内容",
                    "type": "string"
                },
                "server_name": {
                    "description": "server_name 服务名 必填",
                    "type": "string"
                },
                "set_id": {
                    "description": "set_id  set id",
                    "type": "string"
                },
                "tag": {
                    "description": "tag  模板唯一标示 默认为 服务名+版本名+zone+set",
                    "type": "string"
                },
                "type": {
                    "description": "type  类型 default 为基础模板",
                    "type": "string"
                },
                "version": {
                    "description": "version  版本",
                    "type": "string"
                },
                "zone_id": {
                    "description": "zone_id  zone id",
                    "type": "string"
                }
            }
        },
        "model.CreateMainJobRequestInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isSql": {
                    "type": "boolean"
                },
                "planId": {
                    "type": "integer"
                },
                "planName": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "regionIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "subJob": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SubJob"
                    }
                }
            }
        },
        "model.CreateMainJobResInfo": {
            "type": "object",
            "properties": {
                "mainJobId": {
                    "type": "integer"
                }
            }
        },
        "model.CreatePlanRequestInfo": {
            "type": "object",
            "properties": {
                "accessId": {
                    "type": "integer"
                },
                "projectId": {
                    "type": "integer"
                },
                "regionIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "templateId": {
                    "type": "integer"
                }
            }
        },
        "model.CreateSubJobReqInfo": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "string"
                },
                "mainJobId": {
                    "type": "integer"
                },
                "moduleId": {
                    "type": "integer"
                },
                "rank": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.PlanResponseInfo": {
            "type": "object",
            "properties": {
                "planId": {
                    "type": "integer"
                }
            }
        },
        "model.QueryMainJobResInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isSql": {
                    "type": "boolean"
                },
                "planId": {
                    "type": "integer"
                },
                "planName": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "regionIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "subJob": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SubJob"
                    }
                }
            }
        },
        "model.QueryPlanResponseInfo": {
            "type": "object"
        },
        "model.QuerySubJobResInfo": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mainJobId": {
                    "type": "integer"
                },
                "moduleId": {
                    "type": "integer"
                },
                "rank": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.SubJob": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mainJobId": {
                    "type": "integer"
                },
                "moduleId": {
                    "type": "integer"
                },
                "rank": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
