// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/record": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Ian"
                ],
                "parameters": [
                    {
                        "description": "1",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/params.CreateIanRequestInfo"
                        }
                    }
                ]
            }
        }
    },
    "definitions": {
        "params.CreateIanRequestInfo": {
            "type": "object",
            "properties": {
                "BETre": {
                    "type": "object",
                    "properties": {
                        "chair": {
                            "type": "integer"
                        },
                        "core": {
                            "type": "integer"
                        },
                        "easy_burpee": {
                            "type": "integer"
                        },
                        "runner": {
                            "type": "integer"
                        },
                        "squat": {
                            "type": "integer"
                        },
                        "stretch": {
                            "type": "integer"
                        },
                        "support": {
                            "type": "integer"
                        }
                    }
                },
                "body": {
                    "type": "object",
                    "properties": {
                        "weight": {
                            "type": "integer"
                        }
                    }
                },
                "name": {
                    "type": "string"
                },
                "worker": {
                    "type": "object",
                    "properties": {
                        "vol1": {
                            "type": "string"
                        },
                        "vol2": {
                            "type": "string"
                        },
                        "vol3": {
                            "type": "string"
                        },
                        "vol4": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
